#!/bin/bash
set -f

if [ `uname -s` = 'Darwin' ]; then
    if [ -z $JAVA_HOME ]; then
	JAVA_HOME=`/usr/libexec/java_home`
    fi
fi

case "$1" in
  -h|--help|"")
    echo "$0 should be run by emacs plugin. M-x ensime should start the server for you"
    exit 1
  ;;
  *)
    PORT_FILE=$1
  ;;
esac

if [ "$ENSIME_JVM_ARGS" == "" ]
then
  ENSIME_JVM_ARGS="-Xms256M -Xmx1512M -XX:PermSize=128m -Xss1M -Dfile.encoding=UTF-8"
fi

BOOTCLASSPATH=<RUNTIME_BOOTCLASSPATH>
CLASSPATH=<RUNTIME_CLASSPATH>
CMD="java -Xbootclasspath/a:${BOOTCLASSPATH} -classpath ${CLASSPATH} ${ENSIME_JVM_ARGS} org.ensime.server.Server ${PORT_FILE}"
echo $CMD
exec $CMD

